apiVersion: v1
kind: Pod
metadata:
  name: maven-pod
  labels:
    app: maven-hello-world
spec:
  containers:
    - name: maven
      image: parth252000/maven-project
      ports:
      - name: maven-port
        containerPort: 3900
