apiVersion: v1
kind: pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginix:latest
    ports:
    - containerPort: 80
  - name: webwatcher
    image: afakharany/watcher:latest
