apiVersion: v1
kind: PersistentVoulume
metadata:
  name: task-pv-volume
  lables:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnces
  hostPath:
    path: "/mnt/data"
